# EcoPackAI

## Importing Libraries

In [35]:
import pandas as pd
import numpy as np
import openpyxl
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

## Loading the Dataset

In [36]:
df = pd.read_excel("dataset/EcoPackAI_Final_2.xlsx")

## Explore the Dataset

In [37]:
print("Preview of Dataset")
display(df.head())

Preview of Dataset

,Material_Type,Product_Type,Cost (USD),Industry,Strength (1-10),Weight Capacity (kg),Biodegradability Score (1-10),CO2 Emission (kg CO2/kg),Recyclability (%)
0,Aluminum,Furniture Carton,3.62,Furniture,10,31.70,1,3.488,95.29
1,Bagasse Fiber,Pizza Box,2.42,Food Packaging,7,6.19,9,0.488,80.83
2,Mushroom Packaging,Board Game Box,2.88,Toys,5,14.17,10,0.269,65.82
3,Glass,Fabric Wrap,4.39,Textiles,10,35.70,1,1.848,96.91
4,PLA Bioplastic,Hardware Container,1.31,Construction,6,15.29,6,1.185,68.84

In [38]:
# Info about columns and datatypes
print("\nDataset Info:")
print(df.info())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Material_Type                  9000 non-null   object
 1   Product_Type                   9000 non-null   object
 2   Cost (USD)                     9000 non-null   float64
 3   Industry                       9000 non-null   object
 4   Strength (1-10)                9000 non-null   int64
 5   Weight Capacity (kg)           9000 non-null   float64
 6   Biodegradability Score (1-10)  9000 non-null   int64
 7   CO2 Emission (kg CO2/kg)       9000 non-null   float64
 8   Recyclability (%)              9000 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 632.9+ KB
None

In [39]:
# Descriptive statistics
print("\nDescriptive Statistics:")
display(df.describe())

Descriptive Statistics:

,Cost (USD),Strength (1-10),Weight Capacity (kg),Biodegradability Score (1-10),CO2 Emission (kg CO2/kg),Recyclability (%)
count,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,2.346962,7.474778,18.720841,6.054333,1.362762,83.502024
std,1.286707,1.725664,8.561454,3.318859,0.996553,13.042673
min,0.300000,4.000000,5.010000,1.000000,0.230000,50.000000
25%,1.330000,6.000000,11.620000,2.000000,0.550000,74.370000
50%,2.120000,7.000000,16.770000,7.000000,1.069500,86.905000
75%,3.120000,9.000000,25.522500,9.000000,2.003500,94.852500
max,6.000000,10.000000,39.980000,10.000000,3.656000,100.000000

In [40]:
# Missing values check
print("\nMissing Values per Column:")
print(df.isnull().sum())

Missing Values per Column:
Material_Type                    0
Product_Type                     0
Cost (USD)                       0
Industry                         0
Strength (1-10)                  0
Weight Capacity (kg)             0
Biodegradability Score (1-10)    0
CO2 Emission (kg CO2/kg)         0
Recyclability (%)                0
dtype: int64

In [41]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (9000, 9)

In [42]:
#Encoding Categorical Values
df = pd.get_dummies(
    df,
    columns=["Material_Type", "Product_Type", "Industry"],
    drop_first=True
)

In [43]:
#feature and target selection
X = df.drop("CO2 Emission (kg CO2/kg)", axis=1)
y = df["CO2 Emission (kg CO2/kg)"]

In [44]:
#train , test set split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

Training set size: (7200, 54)
Testing set size: (1800, 54)

In [45]:
#feature scaling
scaler = StandardScaler()
numerical_cols = [
    "Strength (1-10)",
    "Weight Capacity (kg)",
    "Biodegradability Score (1-10)",
    "Recyclability (%)",
    "Cost (USD)"
]
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

In [46]:
#processed file
df.to_csv("EcoPackAI_Preprocessed.csv", index=False)